version = 0.1

extensions = [
  'https://gist.githubusercontent.com/JayaKrishnaNamburu/4c914a527381d586fb697812c32459d0/raw/teleportHQ.js'
]

default-task = 'build'

[template-options.npm]
auto-install = true

[[task]]
name = 'build'
template = 'teleportHQ'
[task.template-options]
entry = './index.js'