version = 0.1

extensions = ['chomp@0.1:swc', 'chomp@0.1:rollup']

default-task = 'build'

[template-options.npm]
auto-install = true

[[task]]
name = 'build'
deps = ['build:html', 'build:css', 'build:tsx', 'build:ts', 'build:jsx', 'build:js', 'build:rollup']

[[task]]
name = 'build:rollup'
target = 'dist'
deps = ['lib/**/*.js', 'npm:install']
template = 'rollup'
[task.template-options]
entries = [
    'lib/index.js'
]

[[task]]
name = 'build:html'
target = 'lib/#.html'
deps = ['#.html']
run = 'cp $DEP $TARGET'

[[task]]
name = 'build:css'
target = 'lib/#.css'
deps = ['src/#.css']
run = 'cp $DEP $TARGET'

[[task]]
name = 'build:js'
target = 'lib/#.js'
deps = ['src/#.js']
template = 'swc'
[task.template-options.config]
inlineSourcesContent = false
'jsc.target' = 'es2019'
'jsc.parser.jsx' = true
'jsc.parser.syntax' = 'ecmascript'

[[task]]
name = 'build:jsx'
target = 'lib/#.js'
deps = ['src/#.jsx']
template = 'swc'
[task.template-options.config]
inlineSourcesContent = false
'jsc.target' = 'es2019'
'jsc.parser.jsx' = true
'jsc.parser.syntax' = 'ecmascript'

[[task]]
name = 'build:ts'
target = 'lib/#.js'
deps = ['src/#.ts']
template = 'swc'
[task.template-options.config]
inlineSourcesContent = false
'jsc.target' = 'es2019'

[[task]]
name = 'build:tsx'
target = 'lib/#.js'
deps = ['src/#.tsx']
template = 'swc'
[task.template-options.config]
inlineSourcesContent = false
'jsc.target' = 'es2019'